#!/usr/bin/env python3
"""
The Stockbook mark, drawn once and emitted everywhere it is needed.

The iOS icon is the original: a ledger book, lighter spine on the left, three
rows of decreasing length. Everything here is that same mark, and the proportions
live in one place so the launcher icon, the Play listing icon and the feature
graphic cannot drift apart.

What Android changes is the *size*, not the drawing. An adaptive icon is a 108dp
canvas of which only the centre 66dp is guaranteed to survive the launcher's
mask, so the book is drawn smaller here than on iOS — where it fills 65% of the
canvas — or its corners would be sliced off on any launcher using a circle.

    python3 tools/make_play_assets.py

Writes the vector drawables under `android/app/src/main/res/` and the PNGs under
`play/`. Rerun after changing anything below; nothing is edited by hand.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "android/app/src/main/res"
PLAY = ROOT / "play"
FONTS = Path("/mnt/skills/examples/canvas-design/canvas-fonts")

# --- The palette, sampled from the iOS icon so the two apps ship one mark.

BG_FROM = "#2A2740"   # top left
BG_TO = "#171827"     # bottom right, and the app's own `Nocturne.bg`
SPINE = "#9184D9"     # Nocturne accent
BODY = "#5D5294"
ROW = "#D2CEFD"

# --- The mark, as fractions of the book's own box.
#
# Measured off the 1024px iOS icon, so every rendering below is the same drawing
# at a different size.

SPINE_FRACTION = 0.222      # of the book's width
CORNER_FRACTION = 0.103     # of the book's width
ROW_LEFT = 0.354            # of the book's width, from its left edge
ROW_RIGHTS = (0.891, 0.788, 0.666)
ROW_HEIGHT = 0.097          # of the book's height
ROW_CENTRES = (0.290, 0.502, 0.708)

# On iOS the book fills this much of the square canvas.
IOS_BOOK_W = 604 / 1024
IOS_BOOK_H = 662 / 1024

# On Android it has to fit the 66/108 safe zone with room to spare.
ADAPTIVE_BOOK_W = 53 / 108
ADAPTIVE_BOOK_H = 58 / 108


def book_box(canvas: float, width_fraction: float, height_fraction: float):
    """The book's rectangle, centred on a square canvas."""
    w = canvas * width_fraction
    h = canvas * height_fraction
    return (canvas - w) / 2, (canvas - h) / 2, w, h


def rows(x, y, w, h):
    """The three bars, as `(x0, y0, x1, y1, radius)`."""
    height = h * ROW_HEIGHT
    left = x + w * ROW_LEFT
    for right_fraction, centre_fraction in zip(ROW_RIGHTS, ROW_CENTRES):
        centre = y + h * centre_fraction
        yield left, centre - height / 2, x + w * right_fraction, centre + height / 2, height / 2


# --- Vector path data


def rounded_rect_path(x, y, w, h, r):
    """A rounded rectangle as Android `pathData`, clockwise from the top left."""
    return (
        f"M{x + r:.2f},{y:.2f} "
        f"H{x + w - r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x + w:.2f},{y + r:.2f} "
        f"V{y + h - r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x + w - r:.2f},{y + h:.2f} "
        f"H{x + r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x:.2f},{y + h - r:.2f} "
        f"V{y + r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x + r:.2f},{y:.2f} Z"
    )


def spine_path(x, y, w, h, r, spine_w):
    """The book's left band: rounded down its outer edge, square where it meets the page."""
    return (
        f"M{x + spine_w:.2f},{y:.2f} "
        f"H{x + r:.2f} A{r:.2f},{r:.2f} 0 0 0 {x:.2f},{y + r:.2f} "
        f"V{y + h - r:.2f} A{r:.2f},{r:.2f} 0 0 0 {x + r:.2f},{y + h:.2f} "
        f"H{x + spine_w:.2f} Z"
    )


def write_vectors():
    x, y, w, h = book_box(108, ADAPTIVE_BOOK_W, ADAPTIVE_BOOK_H)
    r = w * CORNER_FRACTION
    spine_w = w * SPINE_FRACTION

    row_paths = [
        rounded_rect_path(x0, y0, x1 - x0, y1 - y0, rr)
        for x0, y0, x1, y1, rr in rows(x, y, w, h)
    ]

    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/make_play_assets.py — do not edit by hand. -->\n"
    )
    size = (
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
    )

    foreground = header + (
        "<!--\n"
        "  The ledger book, at the size Android's mask allows.\n"
        "\n"
        "  Only the centre 66 of these 108 units is guaranteed to survive a\n"
        "  launcher's shape, so the book is drawn smaller than on iOS rather than\n"
        "  losing its corners to a circle.\n"
        "-->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n' + size
        + f'    <path\n        android:fillColor="{BODY}"\n'
        f'        android:pathData="{rounded_rect_path(x, y, w, h, r)}" />\n'
        + f'    <path\n        android:fillColor="{SPINE}"\n'
        f'        android:pathData="{spine_path(x, y, w, h, r, spine_w)}" />\n'
        + "".join(
            f'    <path\n        android:fillColor="{ROW}"\n        android:pathData="{p}" />\n'
            for p in row_paths
        )
        + "</vector>\n"
    )

    background = header + (
        "<!-- The app's own background, corner to corner. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n' + size
        + '    <path android:pathData="M0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n'
        '                android:type="linear"\n'
        '                android:startX="0"\n'
        '                android:startY="0"\n'
        '                android:endX="108"\n'
        '                android:endY="108"\n'
        f'                android:startColor="{BG_FROM}"\n'
        f'                android:endColor="{BG_TO}" />\n'
        "        </aapt:attr>\n"
        "    </path>\n"
        "</vector>\n"
    )

    # Android 13+ themed icons: one silhouette the system tints. The rows are
    # holes rather than a second colour, because a monochrome layer has only one.
    monochrome = header + (
        "<!--\n"
        "  The themed-icon silhouette. One path, even-odd, so the three rows read\n"
        "  as holes punched through the book rather than as a colour the system\n"
        "  will not honour.\n"
        "-->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n' + size
        + '    <path\n        android:fillColor="#000000"\n'
        '        android:fillType="evenOdd"\n'
        f'        android:pathData="{rounded_rect_path(x, y, w, h, r)} '
        + " ".join(row_paths)
        + '" />\n'
        "</vector>\n"
    )

    adaptive = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/make_play_assets.py — do not edit by hand. -->\n"
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@drawable/ic_launcher_background" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
        "</adaptive-icon>\n"
    )

    (RES / "drawable/ic_launcher_foreground.xml").write_text(foreground)
    (RES / "drawable/ic_launcher_background.xml").write_text(background)
    (RES / "drawable/ic_launcher_monochrome.xml").write_text(monochrome)
    (RES / "mipmap-anydpi-v26/ic_launcher.xml").write_text(adaptive)
    (RES / "mipmap-anydpi-v26/ic_launcher_round.xml").write_text(adaptive)


# --- Raster


def gradient(size, frm, to):
    """A diagonal wash, drawn small and scaled up — it has no detail to lose."""
    w, h = size
    small = Image.new("RGB", (64, 64))
    fr = tuple(int(frm[i:i + 2], 16) for i in (1, 3, 5))
    to_ = tuple(int(to[i:i + 2], 16) for i in (1, 3, 5))
    pixels = small.load()
    for yy in range(64):
        for xx in range(64):
            t = (xx + yy) / 126
            pixels[xx, yy] = tuple(round(fr[i] + (to_[i] - fr[i]) * t) for i in range(3))
    return small.resize((w, h), Image.BICUBIC)


def draw_book(draw, x, y, w, h, scale=1):
    """The mark, at whatever size, onto an existing canvas."""
    r = w * CORNER_FRACTION
    draw.rounded_rectangle([x, y, x + w, y + h], radius=r, fill=BODY)
    draw.rounded_rectangle(
        [x, y, x + w * SPINE_FRACTION * 2, y + h],
        radius=r,
        fill=SPINE,
        corners=(True, False, False, True),
    )
    # The spine is drawn double-width and then cut back, so its right edge stays
    # square where it meets the page while its outer corners stay round.
    draw.rectangle([x + w * SPINE_FRACTION, y, x + w * SPINE_FRACTION * 2, y + h], fill=BODY)
    for x0, y0, x1, y1, rr in rows(x, y, w, h):
        draw.rounded_rectangle([x0, y0, x1, y1], radius=rr, fill=ROW)


def write_pngs():
    PLAY.mkdir(exist_ok=True)
    supersample = 4

    # The Play listing icon: 512×512, opaque, unmasked — Google rounds it itself.
    # Drawn at the iOS proportions rather than the launcher's, because nothing
    # masks this one.
    size = 512 * supersample
    icon = gradient((size, size), BG_FROM, BG_TO)
    draw = ImageDraw.Draw(icon)
    draw_book(draw, *book_box(size, IOS_BOOK_W, IOS_BOOK_H))
    icon.resize((512, 512), Image.LANCZOS).save(PLAY / "icon-512.png")

    # The feature graphic: 1024×500, opaque. Play crops and overlays it in
    # several places, so everything that matters stays well inside the middle.
    fw, fh = 1024 * supersample, 500 * supersample
    feature = gradient((fw, fh), BG_FROM, BG_TO)
    draw = ImageDraw.Draw(feature)

    mark = 250 * supersample
    mx, my = 96 * supersample, (fh - mark * IOS_BOOK_H / IOS_BOOK_W) / 2
    bw = mark
    bh = mark * (IOS_BOOK_H / IOS_BOOK_W)
    draw_book(draw, mx, my, bw, bh)

    title = ImageFont.truetype(str(FONTS / "InstrumentSans-Bold.ttf"), 78 * supersample)
    body = ImageFont.truetype(str(FONTS / "InstrumentSans-Regular.ttf"), 34 * supersample)

    tx = mx + bw + 72 * supersample
    draw.text((tx, fh / 2 - 62 * supersample), "Stockbook", font=title, fill="#E9E9ED")
    draw.text(
        (tx, fh / 2 + 14 * supersample),
        "Stock and billing for one shop.\nWorks with no signal, ever.",
        font=body,
        fill="#9AA0B4",
        spacing=14 * supersample,
    )

    feature.resize((1024, 500), Image.LANCZOS).save(PLAY / "feature-graphic.png")


if __name__ == "__main__":
    write_vectors()
    write_pngs()
    print("wrote launcher vectors and play/ assets")
